apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rancheros-operator
rules:
- apiGroups:
  - rancheros.cattle.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - fleet.cattle.io
  resources:
  - 'bundles'
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - 'settings'
  verbs:
  - 'get'
  - 'watch'
  - 'list'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
    #resourceNames:
    #- managedosimages.rancheros.cattle.io
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - 'list'
  - 'get'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rancheros-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rancheros-operator
subjects:
- kind: ServiceAccount
  name: rancheros-operator
  namespace: {{.Release.Namespace}}
