name: "LiveCD Detection"
stages:
   rootfs.before:
     - if: |
            cat /proc/cmdline | grep -q "CDLABEL" || cat /proc/cmdline | grep -q "rd.cos.disable"
       name: "Identify live mode"
       files:
       - path: /run/cos/live_mode
         content: "1"
         permissions: 0600
         owner: 0
         group: 0