name: "ROS Rootfs Layout Settings"
stages:
  initramfs:
    - if: '[ ! -f /run/cos/recovery_mode ]'
      commands:
      - |
        if [ ! -e /usr/local/etc/hostname ]; then
          echo rancher-${RANDOM} > /usr/local/etc/hostname
        fi
        ln -sf /usr/local/etc/hostname /etc/hostname
  rootfs:
    - if: '[ ! -f "/run/cos/recovery_mode" ]'
      name: "Layout configuration"
      environment_file: /run/cos/cos-layout.env
      environment:
        VOLUMES: "LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local"
        OVERLAY: "tmpfs:25%"
        RW_PATHS: "/var /etc /srv"
        PERSISTENT_STATE_PATHS: >-
          /etc/systemd
          /etc/rancher
          /etc/ssh
          /etc/iscsi 
          /etc/cni
          /home
          /opt
          /root
          /usr/libexec
          /var/log
          /var/lib/rancher
          /var/lib/kubelet
          /var/lib/wicked
          /var/lib/longhorn
          /var/lib/cni
        PERSISTENT_STATE_BIND: "true"
  rootfs.before:
    # Try to get network before trying to fetch datasource from the net
    - commands:
      - wicked ifup eth0
    - &datasource
      name: "Pull data from provider"
      datasource:
        providers: ["cdrom", "gcp", "openstack", "aws", "azure", "hetzner", "packet", "scaleway", "vultr", "digitalocean", "metaldata" ]
        path: "/oem"
    # Ensures that if no userdata is found at this stage,
    # we retry later and run the boot hook
    # This is relevant only on first-boot
    # Mind that userdata can be in the standard cloud-init syntax.
    # If we don't find any userdata at this stage (because no network is present)
    # We source the respective fields afterwards
    - if: '[ ! -f /oem/userdata ]'
      files:
      - path: /oem/userdata_load
  rootfs.after:
    - if: '[ ! -f /run/cos/recovery_mode ] && [ ! -f /run/cos/live_mode ]'
      name: "Grow persistent"
      layout:
        device:
          label: COS_PERSISTENT
        expand_partition:
  network:
    - <<: *datasource
    # Trigger /oem/userdata if was fetched late
    # when network was available
    # This is relevant only on first-boot
    - if: '[ -f /oem/userdata ] && [ -f /oem/userdata_load ]'
      commands:
      - elemental cloud-init -s initramfs /oem/userdata
      - elemental cloud-init -s boot /oem/userdata
      - rm -rf /oem/userdata_load
  fs.before:
    - if: '[ ! -f "/run/cos/recovery_mode" ] && [ ! -f /run/cos/live_mode ]'
      name: "Grow persistent fs"
      commands:
      - /usr/sbin/partprobe
      - /usr/sbin/resize2fs $(/usr/sbin/blkid -L COS_PERSISTENT)
